export const BaseURL = "http://localhost:8081"
export const PathToCreateAccount = "/accounts/createAccount"
export const LinkAccountNumGen = "/AccountNumberGeneration"
export const LinkRegister = "/Register"
export const RegisterPageLink = "./Register"
